### ISSUE TITLE
TCC Database structure is unknown (e3a2181c14)

### ISSUE THREAD

**Issue by trueToastedCode** [jacobsalmela/tccutil#63]
aarch64 MacOS 14.0

**Comment by jacobsalmela** [comment]
Sounds right.  We need to discover the structure and adjust the code as needed.  I think this pairs with #62 in finding and mapping out the structure of each version of macOS

**Comment by roblabla** [comment]
This got fixed in https://github.com/jacobsalmela/tccutil/pull/66

**Comment by tshu-w** [comment]
Hi, I'm still facing this issue when using the latest version.

+ macOS: 14.5 (23F79)
+ `tccutil`: 1.4.0

**Comment by SuCicada** [comment]
> Hi, I'm still facing this issue when using the latest version.
> 
> * macOS: 14.5 (23F79)
> * `tccutil`: 1.4.0

You need manual clone and run tccutil.py

**Comment by jacobsalmela** [comment]
Yeah, I need to do a homebrew bump PR, but life.  Also need a better mechanism to update the version.  A lot has changed in the python landscape since I made this (and I was not very knowledgeable on python packaging at the time either)
